# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  testSortRoutines:
    # Specify the execution environment. 
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run:
          name: "Apt update"
          command: sudo apt update 
      - run:
          name: "Install cppcheck"
          command: sudo apt install -y cppcheck 
      - run:
          name: "Install valgrind"
          command: sudo apt install -y valgrind
      - run:
          name: "Install gcovr"
          command: sudo apt install -y gcovr
      - run:
          name: "Open Test Dir"
          command: cd 
      - run:
          name: "Test Routine"
          command: ls -a
      - run:
          name: "Test Routine Make"
          command: make

workflows:
  testSortRoutine-workflow:
    jobs:
      - testSortRoutines
